### ISSUE TITLE
SMS window not shown

### ISSUE THREAD

**Issue by ZigaJanez** [omorandi/TiSMSDialog#10]
Hi I use Titanium SDK 3.2.2.GA and developing an app that will also send SMS.
On Android it's working but on iPhone (simulator) there is no action - nothing happens. Also my error log is empty.
Any suggestion?

**Comment by rgaushell** [comment]
Try it on a real phone.  The simulator has weird behavior with iMessage.

**Comment by ZigaJanez** [comment]
I will try thx for hint,

**Comment by omorandi** [comment]
Hi, running on the simulator is not supported by the module. Please, check out the updated example and test it on a real device
