### ISSUE TITLE
Operation cancelled?

### ISSUE THREAD

**Issue by gigawing** [omorandi/TiSMSDialog#14]
Hi mr Omorandi! 

First of all: thank you for sharing this module. 

But I have a problem... Do you know what´s causing the result message "Operation cancelled"? We are running the app on a phone (not simulator) and the complete handler triggers. We have tried with several different phonenumbers and different phones.

OS: iOS7
SDK: 3.2.3.GA

**Comment by omorandi** [comment]
The "canceled" event should be triggered when you tap the cancel button in the message composer view. Are you seeing it fired in other cases? Can you be more specific on the issue you're experiencing and report how it can be reproduced?
Thank you.

**Comment by gigawing** [comment]
I have made further test and it seems that the phonenumbers I get from Ti.Contacts has some weird formatting. I tried hard coding the same number I got from Ti.Contacts as a string and your module worked fine. I still don´t know why they don´t work but, as far I can see, this is not a problem on behalf of your module. Thank you for your time. Any tips are appreciated :)

Anyway, this is the code I use - I think you recognize most of it :)

``` javascript
var phoneNumber = contact.phone.iPhone ? contact.phone.iPhone : contact.phone.mobile;
alert( phoneNumber ); // if I hardcode this value it works...
var smsDialog = SMSModule.createSMSDialog();

    //check if the feature is available on the device at hand
    if (!smsDialog.isSupported())
    {
        //falls here when executed on iOS versions < 4.0 and in the emulator
        var a = Ti.UI.createAlertDialog({title: 'warning', message: 'the required feature is not available on your device'});
            a.show();
    }
    else
    {
        //pre-populate the dialog with the info provided in the following properties
        smsDialog.recipients = [phoneNumber];
        smsDialog.messageBody = 'Hejje! Spela mot mig!';

        //set the color of the title-bar
        smsDialog.barColor = 'red';

    //add an event listener for the 'complete' event, in order to be notified about the result of the operation
        smsDialog.addEventListener('complete', function(e){

        var a = Ti.UI.createAlertDialog({title: 'SMS', message: "Result: " + e.resultMessage});
            a.show();

           if (e.result == smsDialog.SENT) {
               //do something
           }else if (e.result == smsDialog.FAILED) {
                 //do something else
           }else if (e.result == smsDialog.CANCELLED) {
                 //don't bother
           }
       });

        //open the SMS dialog window with slide-up animation
        smsDialog.open({animated: false});

 }
```

**Comment by gigawing** [comment]
Sooooo, where I set the phonenumber I should have written:

var phoneNumber = dataItem.phone.iPhone[0] ? dataItem.phone.iPhone[0] : dataItem.phone.mobile[0];

...since those parameters can have several elements. *Facepalm.

Thank for your time. And your module. Cheers.

**Comment by omorandi** [comment]
I'm glad you could get this sorted out. Self-closing issues are my favourites ;-)

**Comment by gigawing** [comment]
And the code I posted isn´t robust... This one is better:

``` javascript
        var phoneNumber = null;

        for(var pKey in dataItem.phone) {

            for(var key in dataItem.phone[pKey])
            {
                phoneNumber = dataItem.phone[pKey][key];

                if(phoneNumber != null)
                    break;
            }

            if(phoneNumber != null)
                    break;
        }
```

Cheers :)
