### ISSUE TITLE
Build Error on 1.6

### ISSUE THREAD

**Issue by baldrailers** [omorandi/TiSMSDialog#3]
First of all, great work!

I'm having an issue building this using build.py, my current setup is 1.6.2

https://gist.github.com/469d5436b0cca2cc8ee5

Thanks!

**Comment by omorandi** [comment]
Hi Julius, 
thanks!
I just updated the readme notice, stating that the current revision only supports 1.7.1 and above. I also added a branch (Ti-1.6.2) for handling previous versions of the Ti SDK (from 1.4.3 to 1.6.2), so you can check that out. I also added the built package to both branches. I hope this will fix your problems.
Have a nice day!

**Comment by baldrailers** [comment]
Awesome works like charm. I haven't had a chance to migrate my codes yet to 1.7.x so i'll stick with 1.6.2

I'll play along with the module and will file issues if i stumble upon them.

have a great day!
