### ISSUE TITLE
Dialog shows as supported when running on iPod Touch

### ISSUE THREAD

**Issue by greenSkin** [omorandi/TiSMSDialog#4]
I've noticed that the smsDialog.isSupported() returns true on my wife's iPod Touch.

**Comment by omorandi** [comment]
Hi, can you please give more information on the iPod model and iOS version? Thanks, I'll look into it.

**Comment by greenSkin** [comment]
It's an iPd Touch 3rd generation currently running iOS 5.

**Comment by greenSkin** [comment]
Apparently not an issue anymore. Not sure exactly what had changed other than I'm running iOS 5 on the iPod. Perhaps a change in iOS 5.
