### ISSUE TITLE
messageBody property doesn't accepte localized strings

### ISSUE THREAD

**Issue by Skoua** [omorandi/TiSMSDialog#7]
Hello,

When trying to use a localized text for messageBody, the string id is displayed but never does the translated string.

```
var sms = require('com.omorandi'),
smsDialog = sms.createSMSDialog();

if(smsDialog.isSupported())
{
    smsDialog.messageBody = L('share-subject');
    smsDialog.open({animated: true});
}
```

This example results in "share-subject" being displayed in the body instead of the right text.

I've tested this in iOS 7.0.3 and Ti SDK 3.1.3 and 3.2.0.

Thanks!

**Comment by omorandi** [comment]
This issue is likely related to Titanium, not the module. In general, when the L() function doesn't return the expected localized string it's because you have to clean and rebuild the Ti project.

**Comment by Skoua** [comment]
Ok my string id wasn't correct in the language I was testing, sorry for the noob report.

Thanks!
