### ISSUE TITLE
the 'com.omorandi'  module is not supported by titanium SDK 3.2.2.GA

### ISSUE THREAD

**Issue by odinmaster06** [omorandi/TiSMSDialog#9]
hi,
when i add module in tiapp.xml,
i see this message " the 'com.omorandi'  module is not supported by titanium SDK 3.2.2.GA" in  list of modules and when i test -> open a white window :/ 

help me please

**Comment by omorandi** [comment]
Please, check out if the updated version of the module fixes your problems.
